-- MySQL Script generated by MySQL Workbench
-- Tue Oct 25 21:18:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema daniel2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema daniel2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `daniel2` DEFAULT CHARACTER SET utf8mb4 ;
USE `daniel2` ;

-- -----------------------------------------------------
-- Table `daniel2`.`eleitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `daniel2`.`eleitor` (
  `titulo_eleitoral_eleitor` INT(11) ZEROFILL NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`titulo_eleitoral_eleitor`),
  UNIQUE INDEX `titulo_eleitoral_UNIQUE` (`titulo_eleitoral_eleitor` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `senha_UNIQUE` (`senha` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `daniel2`.`candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `daniel2`.`candidato` (
  `numero_candidato` INT(11) NOT NULL,
  `titulo_eleitoral_eleitor` INT(11) NOT NULL,
  `imagem` VARBINARY(8000) NOT NULL,
  `situacao` CHAR(1) NOT NULL,
  PRIMARY KEY (`numero_candidato`),
  INDEX `fk_candidato_eleitor1_idx` (`titulo_eleitoral_eleitor` ASC) VISIBLE,
  CONSTRAINT `fk_candidato_eleitor1`
    FOREIGN KEY (`titulo_eleitoral_eleitor`)
    REFERENCES `daniel2`.`eleitor` (`titulo_eleitoral_eleitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `daniel2`.`voto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `daniel2`.`voto` (
  `idvoto` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo_eleitoral_eleitor` INT(11) ZEROFILL NOT NULL,
  `numero_candidato` INT(11) NOT NULL,
  PRIMARY KEY (`idvoto`),
  INDEX `fk_voto_candidato1_idx` (`numero_candidato` ASC) VISIBLE,
  INDEX `fk_voto_eleitor1_idx` (`titulo_eleitoral_eleitor` ASC) VISIBLE,
  CONSTRAINT `fk_voto_candidato1`
    FOREIGN KEY (`numero_candidato`)
    REFERENCES `daniel2`.`candidato` (`numero_candidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voto_eleitor1`
    FOREIGN KEY (`titulo_eleitoral_eleitor`)
    REFERENCES `daniel2`.`eleitor` (`titulo_eleitoral_eleitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO eleitor VALUES (00000000000, 'Branco', 'admin', '123');